org: vandenthom
app: yummying-bird-serverless-api
service: yummying-bird-serverless-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-3
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: '*'

functions:  
  createUser:
    handler: src/lambda/user/createUser.handler
    events:
      - http:
          path: '/auth/signup'
          method: post
    environment:
      RECIPE_TABLE: 'User'

  login: 
    handler: src/lambda/user/login.handler
    events:
      - http:
          path: '/auth/login'
          method: post
    environment:
      RECIPE_TABLE: 'User'


  createRecipe:
    handler: src/lambda/recipe/createRecipe.handler
    events:
      - http:
          path: '/recipe'
          method: post
    environment:
      RECIPE_TABLE: 'Recipe'

  getRecipes:
    handler: src/lambda/recipe/getRecipes.handler
    events:
      - http:
          path: '/recipes'
          method: get
    environment:
      RECIPE_TABLE: 'Recipe'

  getRecipe:
    handler: src/lambda/recipe/getRecipe.handler
    events:
      - http:
          path: '/recipe/{uuid}'
          method: get
    environment:
      RECIPE_TABLE: 'Recipe'

  updateRecipe:
    handler: src/lambda/recipe/updateRecipe.handler
    events:
      - http:
          path: '/recipe/{uuid}'
          method: put
    environment:
      RECIPE_TABLE: 'Recipe'


resources:
  Resources:
    Recipe:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Recipe
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: uuid
            KeyType: HASH
    User:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: User
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: uuid
            AttributeType: S
          - AttributeName: firstName
            AttributeType: S
          - AttributeName: lastName
            AttributeType: S
          - AttributeName: email
            AttributeType: S
          - AttributeName: password
            AttributeType: S
        KeySchema:
          - AttributeName: uuid
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: email
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL